[package]
name = "imp"
version = "0.0.0"
authors = ["Matt Garnett <14004106+lightclient@users.noreply.github.com>"]
edition = "2018"

[dependencies]
arrayref = "0.3.5"
sha2 = "0.8.0"

[dev-dependencies]
bigint = "4.4.1"

[features]
default = ["std"]
std = []
